# Generated by Django 4.1.3 on 2022-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnab",
            name="cartao",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cnab",
            name="cpf",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cnab",
            name="dono",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cnab",
            name="hora",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cnab",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
